# Generated by Django 3.2.7 on 2022-04-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postmodel_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
